### ISSUE TITLE
Upstream changes in AnalogJ/scrutiny

### ISSUE THREAD

**Issue by AnalogJ** [linuxserver/docker-scrutiny#11]
Hey,

Thanks for all your work building these images, its appreciated :)

I made some pretty big changes to Scrutiny recently, and I thought you might want to update your images/documentation to match:

- [Collector runs once automatically during startup](https://github.com/AnalogJ/scrutiny/blob/master/rootfs/etc/services.d/collector-once/run)
- [Collector config file](https://github.com/AnalogJ/scrutiny/blob/master/example.collector.yaml)
- [Notifications](https://github.com/AnalogJ/scrutiny/blob/master/example.scrutiny.yaml#L36-L55)

**Comment by HiNsKeY** [comment]
> Hey,
> 
> Thanks for all your work building these images, its appreciated :)
> 
> I made some pretty big changes to Scrutiny recently, and I thought you might want to update your images/documentation to match:
> 
> * [Collector runs once automatically during startup](https://github.com/AnalogJ/scrutiny/blob/master/rootfs/etc/services.d/collector-once/run)
> * [Collector config file](https://github.com/AnalogJ/scrutiny/blob/master/example.collector.yaml)
> * [Notifications](https://github.com/AnalogJ/scrutiny/blob/master/example.scrutiny.yaml#L36-L55)

Thank you, I love being able to monitor my servers so easily! I'm new to this but am on the discord asking how to get the image updated. I will then update the documentation to match.

**Comment by vick75017** [comment]
Hello, 
Félicitation  already and thank you for your work. I installed everything correctly, but it happens to find only one (the first one) in five discs of my raid (shr synology). When I go to a smartctl --scan, it finds ": / dev / hda -d ata # / dev / hda, ATA device". I don't know how I can change this, do you have a solution?

**Comment by FlexibleToast** [comment]
This issue has been open for nearly a year and needs to be bumped. Notifications is a pretty critical feature for this. Having a place to look at drive health is great, but without being notified when a drive is failing it's not nearly as useful.

**Comment by aptalca** [comment]
Looks like this issue fell through the cracks. We're looking into it.
Thanks

**Comment by alex-phillips** [comment]
I'm not sure what is missing here that isn't already supported. Any upstream changes that are driven by the config can be made by altering the persisted config as we don't modify it after initialization anyway. I've tested notifications with my LSIO scrutiny instance and that is working fine.

**Comment by FlexibleToast** [comment]
I can confirm that the notify works when editing the persistent configs directly. I expected something exposed through the env variables like many of the other linuxserver apps.
