### ISSUE TITLE
Local hosts aren't being resolved by scrutiny

### ISSUE THREAD

**Issue by asmfreak** [linuxserver/docker-scrutiny#12]
Go DNS resolver respects `/etc/nsswitch.conf` missing in the container.
To fix this issue, you need to add the following line to Dockerfile:
```
printf "hosts: files dns" > /etc/nsswitch.conf
```

## Steps to Reproduce
1. Add a webhook notify to `scrutiny.yaml` pointing to an `extra_hosts` entry from compose file:
`docker-compose.yml`:
```
#...
    extra_hosts:
      - 'some.local.host.li.nk:192.168.10.15'
#...
```
`scrutiny.yml`:
```
#...
notify:
   - "https://some.local.host.li.nk/some/webhook/addr"
#...
```
2. `curl -X POST http://localhost:8080/api/health/notify`
3. `scrutiny` fails in logs with dns error or connect error (if dns lookup was made but the address was incorrect)

## Environment
Any

**Comment by alexbelgium** [comment]
Hi, could you please test the dev2 version? It could have solved the issue. Thanks!
