### ISSUE TITLE
Upgrade upstream v0.3.13

### ISSUE THREAD

**Issue by adripo** [linuxserver/docker-scrutiny#16]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Run latest version 0.3.13

## Current Behavior
Running version 0.3.12

## Steps to Reproduce

1.Run container

## Environment
**OS:** linux
**CPU architecture:** x86_64
**How docker service was installed:**

## Details

Upstream released version 0.3.13 in October 2021, but this image still runs 0.3.12
https://github.com/AnalogJ/scrutiny/releases/tag/0.3.13
Can it be updated?

Thank you

**Comment by pagdot** [comment]
The upstream follows the master branch which is right now v0.4.1. Does this solve this issue?

**Comment by adripo** [comment]
Yes, thank you!
