### ISSUE TITLE
Image doesnt start at all

### ISSUE THREAD

**Issue by TheBroTMv2** [linuxserver/docker-scrutiny#23]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

image should start and work as intended

## Current Behavior

keeps starting again 

## Steps to Reproduce

just pull the container over CA in UnRaid and add /run/udev and privileged
1.
2.
3.
4.

## Environment
**OS:**
Unraid 6.10.2
**CPU architecture:** 
x86_64
**How docker service was installed:**

Comes included in the Unraid OS

## Docker logs

Start the scrutiny server
[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:   export GIN_MODE=release
 - using code:  gin.SetMode(gin.ReleaseMode)

time="2022-05-29T20:19:38+02:00" level=info msg="Successfully connected to scrutiny sqlite db: \n"
panic: failed to check influxdb setup status - parse "://:": missing protocol scheme

goroutine 1 [running]:
github.com/analogj/scrutiny/webapp/backend/pkg/web/middleware.RepositoryMiddleware({0x1020d60, 0xc0000becc8}, {0x102a430, 0xc000370070})
        /app/scrutiny/webapp/backend/pkg/web/middleware/repository.go:14 +0xa5
github.com/analogj/scrutiny/webapp/backend/pkg/web.(*AppEngine).Setup(0xc00036c540, {0x102a430, 0xc000370070})
        /app/scrutiny/webapp/backend/pkg/web/server.go:26 +0xb4
github.com/analogj/scrutiny/webapp/backend/pkg/web.(*AppEngine).Start(0xc00036c540)
        /app/scrutiny/webapp/backend/pkg/web/server.go:99 +0x3ab
main.main.func2(0xc000345ac0)
        /app/scrutiny/webapp/backend/cmd/scrutiny/scrutiny.go:112 +0x1f7
github.com/urfave/cli/v2.(*Command).Run(0xc00036e480, 0xc000345940)
        /app/scrutiny/vendor/github.com/urfave/cli/v2/command.go:164 +0x64a
github.com/urfave/cli/v2.(*App).RunContext(0xc000238480, {0x100b030, 0xc0000c6000}, {0xc0000c2000, 0x2, 0x2})
        /app/scrutiny/vendor/github.com/urfave/cli/v2/app.go:306 +0x926
github.com/urfave/cli/v2.(*App).Run(...)
        /app/scrutiny/vendor/github.com/urfave/cli/v2/app.go:215
main.main()
        /app/scrutiny/webapp/backend/cmd/scrutiny/scrutiny.go:137 +0x679

**Comment by kristof-mattei** [comment]
https://github.com/AnalogJ/scrutiny/blob/0c908786e00d7831cdf4fbf8949c8476dd419e67/docs/TROUBLESHOOTING_INFLUXDB.md#upgrading-from-v03x-to-v04x

I switched to the new image.

**Comment by TheBroTMv2** [comment]
thx, that worked
