### ISSUE TITLE
readme needs updated to correspond with the 0.2.4 release

### ISSUE THREAD

**Issue by kinghat** [linuxserver/docker-scrutiny#7]
with https://github.com/AnalogJ/scrutiny/releases/tag/0.2.4 we can remove `--privileged` for `--cap-add SYS_RAW` or `--cap-add SYS_ADMIN` depending on the type of drives you use.

also, instead of using `-v /dev:/dev` you can specify individual devices `-v /dev/sda:/dev/sda`

the changes are here: https://github.com/AnalogJ/scrutiny/commit/9bd8aec315aea395743890abd9f4fe6f407d145e

**Comment by ironicbadger** [comment]
See #8 PR.
